#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

data = json.load(sys.stdin)

# Setup variables
host = data.get("host", "git.example.org")

agent.set_env("HOST", host)

# Write gitlab.rb Config file
gitlab_config = {
    "GITLAB_EMAIL_DISPLAY_NAME": "Gitlab auf dem Nethserver",
}
agent.write_envfile('gitlab.rb', gitlab_config)