#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
import agent.tasks

data = json.load(sys.stdin)

# Setup variables
host = data.get("host")
ldap_domain = data.get("ldap_domain")
registry_host = data.get("registry_host")
initial_password = data.get("password")
server_port, registry_port = os.environ['TCP_PORTS'].split(",")

if (not os.environ.get('HOST', False) or host != os.environ['HOST']) and agent.http_route_in_use(domain=host):
    agent.set_status('validation-failed')
    json.dump([{'field':'hostname','parameter':'hostname','value':host,'error':'domain_already_used_in_traefik'}],fp=sys.stdout)
    sys.exit(2)

agent.set_env("HOST", host)
agent.set_env("GITLAB_NGINX_PORT", server_port)
agent.set_env("LDAP_DOMAIN", ldap_domain)
agent.set_env("GITLAB_REGISTRY_HOST", registry_host)
agent.set_env("GITLAB_REGISTRY_PORT", registry_port)
agent.set_env("GITLAB_INITIAL_PASSWORD", initial_password)