#!/usr/bin/env python3

#
# Copyright (C) 2024 Philip Falliano
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Configure ldap 

import sys
import os
import agent

cdomain = os.environ['LDAP_DOMAIN']

if not cdomain:
    sys.exit(0)

agent.bind_user_domains([cdomain])
