#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
import agent.tasks

data = json.load(sys.stdin)

# Setup variables
host = os.environ.get('HOST')
registry_url = os.environ.get('GITLAB_REGISTRY_HOST')

default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Configure traefik virtual host
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url': f'http://127.0.0.1:{os.environ["TCP_PORT"]}',
        'host': host,
        'lets_encrypt': True,
        'http2https': True
    },
)

agent.assert_exp(response['exit_code'] == 0)

if registry_url:
    # Configure traefik virtual host
    response = agent.tasks.run(
        agent_id=default_traefik_id,
        action='set-route',
        data={
            'instance': os.environ['MODULE_ID']+'-registry',
            'url': f'http://127.0.0.1:{os.environ["TCP_PORT"]}',
            'host': registry_url,
            'lets_encrypt': True,
            'http2https': True
        },
    )

    agent.assert_exp(response['exit_code'] == 0)