#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# Enable podman socket for gitlab runner
systemctl --user enable --now podman.socket
systemctl --user restart podman.socker

systemctl --user enable --now gitlab.service gitlab-app.service gitlab-runner.service
systemctl --user restart gitlab.service gitlab-app.service gitlab-runner.service