#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
from agent.ldapproxy import Ldapproxy

config = {}

env = f'module/{os.environ["MODULE_ID"]}/environment'
rdb = agent.redis_connect()
config["host"] =  rdb.hget(env, "HOST")
config["lets_encrypt"] =  rdb.hget(env, "LETS_ENCRYPT") == "True"

lp = Ldapproxy()
domains = []
for key in lp.get_domains_list():
    domains.append(key)

config['ldap_domain_list'] = domains
config['ldap_domain'] = rdb.hget(env, "LDAP_DOMAIN")
config['registry_host'] = rdb.hget(env, "GITLAB_REGISTRY_HOST")

json.dump(config, fp=sys.stdout)
