#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

config = {}

env = f'module/{os.environ["MODULE_ID"]}/environment'
rdb = agent.redis_connect()
config["host"] =  rdb.hget(env, "HOST")
config["lets_encrypt"] =  rdb.hget(env, "LETS_ENCRYPT") == "True"

json.dump(config, fp=sys.stdout)
